//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DateTimeServiceClient.ServiceReferenceDate {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceDate.IDateService")]
    public interface IDateService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDateService/GetDay", ReplyAction="http://tempuri.org/IDateService/GetDayResponse")]
        string GetDay(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDateService/GetDay", ReplyAction="http://tempuri.org/IDateService/GetDayResponse")]
        System.Threading.Tasks.Task<string> GetDayAsync(System.DateTime date);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDateServiceChannel : DateTimeServiceClient.ServiceReferenceDate.IDateService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DateServiceClient : System.ServiceModel.ClientBase<DateTimeServiceClient.ServiceReferenceDate.IDateService>, DateTimeServiceClient.ServiceReferenceDate.IDateService {
        
        public DateServiceClient() {
        }
        
        public DateServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DateServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DateServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DateServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetDay(System.DateTime date) {
            return base.Channel.GetDay(date);
        }
        
        public System.Threading.Tasks.Task<string> GetDayAsync(System.DateTime date) {
            return base.Channel.GetDayAsync(date);
        }
    }
}
